### ISSUE TITLE
Normalizar años

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#116]
Algunos años no están bien generados:
0
Ano-2000
2016 como string

http://opendata.aragon.es/sparql?default-graph-uri=&query=select+distinct++%3Fy+where+{%0D%0A%3Fobs+%3Chttp%3A%2F%2Fpurl.org%2Flinked-data%2Fsdmx%2F2009%2Fdimension%23refPeriod%3E+%3Fy%0D%0A}+%0D%0AORDER+BY+%3Fy%0D%0ALIMIT+100&format=text%2Fhtml&timeout=0&debug=on

``` sparql
select distinct  ?y where {
?obs <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?y
} 
ORDER BY ?y
LIMIT 100
```

**Comment by ocorcho** [comment]
Esta query nos dice los cubos en los que hay que investigar:

```
select distinct ?dataset ?y where {
?obs <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?y .
?obs qb:dataSet ?dataset
} 
ORDER BY ?y
```

Concretamente, hay que revisar:

- 04-040012TC, que genera lo de año-2000 (esto se tendrá que cambiar en los datos, avisando a IAEst)
- 01-010025TM, que genera un year 0 (idem)
- 01-010001A, TC, TM y TP, que generan mal el año, como un string. Esto se debe cambiar en la configuración (@hlafuente mira a ver cómo hacerlo y documenta aquí).

**Comment by cescan** [comment]
Revisando esos DS, he visto que todavía falta corregir uno:
01-010025TM
Hay dastos que tienen dos periodos (Ejem: http://opendata.aragon.es/recurso/iaest/observacion/01-010025TM/00d82701-de34-3a09-b5d1-6b516bdb900f  )
Es debido a que hay una columna adicional  "Rústico, año última renovación",  que no es el año del dato, y se está vinculando tambien al refPeriod.
Esa columna se puede ignorar (no es necesaria como dimensión)
