### ISSUE TITLE
Asignar correctamente refPeriod con año y mes

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#118]
Al menos, rellenar correctamente el año (ahora 2011 by default)

``` sparql
select distinct ?refArea ?refPeriod  ?mes_y_ano  ?sexo  ?n_parados   where {
 ?obs qb:dataSet <http://opendata.aragon.es/recurso/iaest/dataset/05-050201A>.
 ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?refPeriod.
FILTER (?refPeriod IN (<http://reference.data.gov.uk/id/year/2011>)).
 ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?refArea.
 OPTIONAL {  ?obs <http://opendata.aragon.es/def/iaest/dimension#mes-y-ano> ?mes_y_ano  } .
OPTIONAL { ?obs <http://opendata.aragon.es/def/iaest/dimension#sexo> ?foo1.
 ?foo1 skos:prefLabel ?sexo  } .
OPTIONAL {  ?obs <http://opendata.aragon.es/def/iaest/medida#n-parados> ?n_parados  } .
} 
ORDER BY ASC(?refArea) ASC(?refPeriod)
LIMIT 200
```

**Comment by dportoles** [comment]
Lista tentativa de informes a los que presumiblemente le pasa esto mismo:

```sparql
select distinct ?dataset  where {
 ?obs qb:dataSet ?dataset.
 ?obs <http://opendata.aragon.es/def/iaest/dimension#mes-y-ano> ?mes_y_ano  .
} 
LIMIT 200
```

**Comment by MiquelQ** [comment]
Query que saca los informes en los que no coincide el  Año(1) con el año de la dimension Mes y Año(2).
El año ahora se pone 2011 por defecto si no viene desde el BI

(1)<http://purl.org/linked-data/sdmx/2009/dimension#refPeriod>
(2)<http://opendata.aragon.es/def/iaest/dimension#mes-y-ano>

Nos puede servir de ayuda para solucionarlo.

`select count(distinct ?dataset)  where {
 ?obs qb:dataSet ?dataset.
 ?obs <http://opendata.aragon.es/def/iaest/dimension#mes-y-ano> ?mes_y_anyo  .
 ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?anyo.
 filter(!regex(?mes_y_anyo, strafter(str(?anyo),"http://reference.data.gov.uk/id/year/") ))
} `

**Comment by ocorcho** [comment]
Claramente el año no es necesario en el caso de que tengamos la dimensión Mes y Año. 
En todos estos casos, lo que debemos hacer es eliminar la columna refPeriod/año que se genera por defecto, dado que ya hay una referencia temporal (pongo aquí en copia a @hlafuente y @MiquelQ por si hay que tocar algo en el código) y hacer que la columna mes-y-ano sea refPeriod y se genere apropiadamente la URI de reference.data.gov.uk, que es, por ejemplo:

http://reference.data.gov.uk/id/month/2011-09

**Comment by ocorcho** [comment]
Asimismo, habría por tanto que eliminar la dimensión http://opendata.aragon.es/def/iaest/dimension#mes-y-ano, pues no es necesaria.

**Comment by dportoles** [comment]
@hlafuente & @MiquelQ:
En cuanto esté listo, por  favor comprobad que la aplicación sigue funcionando. 
Intuyo que habrá que revisar las queries sparql y/o cambiar la aplicación (a ver el impacto que tiene...)

**Comment by hlafuente** [comment]
Buenas! @MiquelQ Creo que es necesario tocar un poco de código pero no mucho. En la clase TransformToRDF.java hay un método addObservation. En este método hay un if 

`if (dataBean.getNormalizacion().equals("sdmx-dimension:refPeriod")) { `

Dentro de este if habrá que separar las fechas que vengan de 'ano' de las que vengan de 'mes-codigo'. En las que el dataBean.getNameNormalized() sea 'ano', hará lo que tiene el if actualmente. En las que el dataBean.getNameNormalized() sea 'mes-codigo', haremos como en 'ano' pero sustituiremos 'http://reference.data.gov.uk/id/year/' por 'http://reference.data.gov.uk/id/month/' y cogerremos normalizedCell y añadiremos un guion entre el año y el mes. Es decir transformaremos 201610 por 2016-10. 

Con estos cambios en código en configuración habrá que rellenar las columnas 'mes-codigo' así:

> Mes (código)
> mes-codigo
> sdmx-dimension:refPeriod
> dim
> xsd:date

A parte de eliminar las columnas 'año' y 'mes y año'.

Un saludo.

**Comment by MiquelQ** [comment]
He aplicado cambios en el código del proceso para que haga lo que se sugiere.

Pero ahora ocurre algo extraño a la hora de visualizarlo con la API

He estado probando, metiendo logs en PRE y no logro ver nada.

El ttl en la carpeta /DatosTTL (el ttl del informe) está correcto, es decir, no tiene year 2011 y tiene month.

Pero luego al visualizarlo de la siguiente manera:
http://preopendata.aragon.es/recurso/iaest/dataset/05-050003TC

Saca el _month_ y el _year_.

Pero si se visualiza de esta manera (añadiendo __sort_, __page_ _y_pageSize_ a la url)
http://preopendata.aragon.es/recurso/iaest/dataset/05-050003TC?_sort=label&_page=0&_pageSize=50

La misma observación se ve que además de mostrar _month_ en refPerido, añade el _year_.

Entonces...me hace sospechar que sea a nivel de visualización (recurso/)
@hlafuente  ¿puede ser?
¿El código de recurso.war lo puedo tocar yo?

Muchas GRacias!!

**Comment by ocorcho** [comment]
Hola @hlafuente

Tiene pinta de ser en la configuración de ELDA.

Es buena idea describir de manera sencilla en la documentación cómo hacer el
cambio, para que así se pueda utilizar en el futuro.
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4b
b","name":"GitHub"},"entity":{"external_key":"github/aragonopendata/local-da
ta-aragopedia","title":"aragonopendata/local-data-aragopedia","subtitle":"Gi
tHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/143
418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"h
ttps://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6
-9aed-b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/aragonopendata/local-data-aragopedia"}},"u
pdates":{"snippets":[{"icon":"PERSON","message":"@MiquelQ in #118: He
aplicado cambios en el código del proceso para que haga lo que se
sugiere.\r\n\r\nPero ahora ocurre algo extraño a la hora de visualizarlo con
la API\r\n\r\nHe estado probando, metiendo logs en PRE y no logro ver
nada.\r\n\r\nEl ttl en la carpeta /DatosTTL (el ttl del informe) está
correcto, es decir, no tiene year 2011 y tiene month.\r\n\r\nPero luego al
visualizarlo de la siguiente
manera:\r\nhttp://preopendata.aragon.es/recurso/iaest/dataset/05-050003TC\r\
n\r\nSaca el _month_ y el _year_.\r\n\r\nPero si se visualiza de esta manera
(añadiendo __sort_, __page_ _y_pageSize_ a la
url)\r\nhttp://preopendata.aragon.es/recurso/iaest/dataset/05-050003TC?_sort
=label\u0026_page=0\u0026_pageSize=50\r\n\r\nLa misma observación se ve que
además de mostrar _month_ en refPerido, añade el
_year_.\r\n\r\nEntonces...me hace sospechar que sea a nivel de visualización
(recurso/)\r\n@hlafuente  ¿puede ser?\r\n¿El código de recurso.war lo puedo
tocar yo?\r\n\r\nMuchas GRacias!!"}],"action":{"name":"View
Issue","url":"https://github.com/aragonopendata/local-data-aragopedia/issues
/118#issuecomment-261280376"}}}

**Comment by hlafuente** [comment]
Yo la configuración de elda la veo bien, ¿Es posible que sea que no esté duplicado en virtuoso?

@Miquel Yo intentaría borrar el grafo 05-050003 y volverlo a ejecutar.

**Comment by MiquelQ** [comment]
He borrado los grafos y vuelto a crear con el proceso.
Sigue pasando lo mismo.
En el TTL no veo ningún "year" en cambio en la visualización si que se ve.
http://preopendata.aragon.es/recurso/iaest/dataset/05-050003TC

Me he dado cuenta, que las observaciones que tienen los 2 refPeriod, no existen si accedes a ellas como observación (ej):
http://preopendata.aragon.es/recurso/iaest/observacion/05-050003TC/008c87c6-c604-3fe9-a13f-529ebdd29000?api_key=e103dc13eb276ad734e680f5855f20c6

**Comment by cescan** [comment]
Actualizados los DS que tenian 'mes-y-ano' añadiendoles  'mes (código)'

Ha tener en cuenta:
 * El informe http://opendata.aragon.es/recurso/iaest/dataset/05-050003TM   tiene datos, pero en la fuente ya no se puede descargar por 'nº máximo registros'   así que se va ha quedar sin actualizarse  (Esto va relacionado con el issue #130 ) Igual convendría quitar este dataset hasta que estuviera solucionado eso.
* Había un par de informes mas: http://opendata.aragon.es/recurso/iaest/dataset/05-050208A y 208TP  que tenían el mes-y-año como medida en vez de dimensión (...eliminar tambien la medida 'mes-y-ano')

**Comment by ocorcho** [comment]
Me parece interesante lo de borrar el dataset que ya no se va a generar,
directamente de GitHub (quedará history, pero eso está bien) y quitarlo del
listado de hash, para que no se regenere.

  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4b
b","name":"GitHub"},"entity":{"external_key":"github/aragonopendata/local-da
ta-aragopedia","title":"aragonopendata/local-data-aragopedia","subtitle":"Gi
tHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/143
418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"h
ttps://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6
-9aed-b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/aragonopendata/local-data-aragopedia"}},"u
pdates":{"snippets":[{"icon":"PERSON","message":"@cescan in #118:
Actualizados los DS que tenian 'mes-y-ano' añadiendoles  'mes
(código)'\r\n\r\nHa tener en cuenta:\r\n * El informe
http://opendata.aragon.es/recurso/iaest/dataset/05-050003TM   tiene datos,
pero en la fuente ya no se puede descargar por 'nº máximo registros'   así
que se va ha quedar sin actualizarse  (Esto va relacionado con el issue #130
) Igual convendría quitar este dataset hasta que estuviera solucionado
eso.\r\n* Había un par de informes mas:
http://opendata.aragon.es/recurso/iaest/dataset/05-050208A y 208TP  que
tenían el mes-y-año como medida en vez de dimensión (...eliminar tambien la
medida 'mes-y-ano')"}],"action":{"name":"View
Issue","url":"https://github.com/aragonopendata/local-data-aragopedia/issues
/118#issuecomment-262770538"}}}

**Comment by MiquelQ** [comment]
Se van aplicando los cambios a los informes con el campo 'Mes y Año'

@dportoles efectivamente, el cambio ha tenido impacto la aplicación. Ahora no salen años para seleccionar si el refPeriod es month. (antes salía solo 2011)

 Por ejemplo en:  http://opendata.aragon.es/recurso/iaest/dataset/05-050201TC?api_key=04d08351bc1bf50c3c65beeb8f8f5b13 (Paro registrado Sexo)

Entonces veo dos opciones:
1) Tocáis la aplicación para que identifique el año del nuevo formato de refPeriod
2) Añadimos a los Informes otro refPeriod con el año, quedando estos informes con 2 refPerdiods.
(es lo que se me ocurre)

El proceso va regenerando los Informes que antes tenían 2011 con default al nuevo campo http://reference.data.gov.uk/id/month/

Me decís.

**Comment by ocorcho** [comment]
Si fuera posible, creo que es más lógico hacer el cambio en la aplicación.
@dportoles ¿puedes confirmar si es posible o necesitas ayuda con las
consultas SPARQL a generar?
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4b
b","name":"GitHub"},"entity":{"external_key":"github/aragonopendata/local-da
ta-aragopedia","title":"aragonopendata/local-data-aragopedia","subtitle":"Gi
tHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/143
418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"h
ttps://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6
-9aed-b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/aragonopendata/local-data-aragopedia"}},"u
pdates":{"snippets":[{"icon":"PERSON","message":"@MiquelQ in #118: Se van
aplicando los cambios a los informes con el campo 'Mes y
Año'\r\n\r\n@dportoles efectivamente, el cambio ha tenido impacto la
aplicación. Ahora no salen años para seleccionar si el refPeriod es month.
(antes salía solo 2011)\r\n\r\n Por ejemplo en:
http://opendata.aragon.es/recurso/iaest/dataset/05-050201TC?api_key=04d08351
bc1bf50c3c65beeb8f8f5b13 (Paro registrado Sexo)\r\n\r\nEntonces veo dos
opciones:\r\n1) Tocáis la aplicación para que identifique el año del nuevo
formato de refPeriod\r\n2) Añadimos a los Informes otro refPeriod con el
año, quedando estos informes con 2 refPerdiods.\r\n(es lo que se me
ocurre)\r\n\r\nEl proceso va regenerando los Informes que antes tenían 2011
con default al nuevo campo http://reference.data.gov.uk/id/month/\r\n\r\nMe
decís.\r\n"}],"action":{"name":"View
Issue","url":"https://github.com/aragonopendata/local-data-aragopedia/issues
/118#issuecomment-264164099"}}}

**Comment by dportoles** [comment]
Creo que podré apañármelas.
Si hay /month/, me quedaré con los 4 siguientes caracteres y supondré que son un /year/.
En todo caso confirmadme si va a haber sólo años y meses en refPeriod o si debo contemplar algún tipo más

Ahora mismo veo que no hay otro tipo pero por dejarlo previsto.

``` sparql
select distinct ?o where {
?s <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?o
} 
ORDER BY ?o
LIMIT 200
```

**Comment by ocorcho** [comment]
En principio no debería haber más tipos, teniendo en cuenta los datos que se
están generando.
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4b
b","name":"GitHub"},"entity":{"external_key":"github/aragonopendata/local-da
ta-aragopedia","title":"aragonopendata/local-data-aragopedia","subtitle":"Gi
tHub 
repository","main_image_url":"https://cloud.githubusercontent.com/assets/143
418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"h
ttps://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6
-9aed-b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/aragonopendata/local-data-aragopedia"}},"u
pdates":{"snippets":[{"icon":"PERSON","message":"@dportoles in #118: Creo
que podré apañármelas.\r\nSi hay /month/, me quedaré con los 4 siguientes
caracteres y supondré que son un /year/.\r\nEn todo caso confirmadme si va a
haber sólo años y meses en refPeriod o si debo contemplar algún tipo
más\r\n\r\nAhora mismo veo que no hay otro tipo pero por dejarlo
previsto.\r\n\r\n``` sparql\r\nselect distinct ?o where {\r\n?s
\u003chttp://purl.org/linked-data/sdmx/2009/dimension#refPeriod\u003e
?o\r\n} \r\nORDER BY ?o\r\nLIMIT 200\r\n```"}],"action":{"name":"View
Issue","url":"https://github.com/aragonopendata/local-data-aragopedia/issues
/118#issuecomment-264193689"}}}

**Comment by cescan** [comment]
Confirmo que todos los datasets actuales tienen año o mes, o sea, no hay más tipos de fechas.

Pero si queréis prevenir... dejamos sin cargar los datos de educación (por ser complejos). Algún día a lo mejor se incluyen y estos deberían llevar fecha de curso "2015/2016". 
¿hay algún tipo para esas fechas?

**Comment by cescan** [comment]
Localizado otro DS que ya no se actualiza por exceso de filas...
http://opendata.aragon.es/recurso/iaest/dataset/05-050009TM
Se puede eliminar como el comentado más arriba (05-050003TM)

**Comment by dportoles** [comment]
Ya lo tengo modificado como creo debería ser. Pero veo que en pre se sigue informando de 2011 para estos informes y en pro dice meses

¿A qué es debido esto? No querría desplegar en pro directamente.

Además, se sigue informando de la dimension:mes-y-ano. La filtro y descarto en la aplicación web, pero creo debería borrarse.

**Comment by MiquelQ** [comment]
Hola buenas, en PRE no está actualizado del todo, como comparten ficheros de configuración...
Lo hago a lo largo del día @dportoles te aviso y así probamos antes en PRE si.

Respecto al tema de las fechas @cescan, creo que el proceso no está preparado para tratar 2 years. 
Habría que modificar tanto proceso como aplicación Web.

**Comment by MiquelQ** [comment]
Salvo los informes que exceden el número máximo de registros se han corregido todos los informes con el campo Mes(código)
El proceso ahora interpretará ese campo como refPeriod correctamente en los informes que se añadan con este.
