### ISSUE TITLE
Añadir en los ficheros de metadatos para la creación de RDF una columna de tipo constante

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#12]
Muchos de los informes tienen como constante el año o trimestre-año en el que han sido generados. Sería útil permitir en estos ficheros de metadatos la inclusión de una columna que permita valores constantes para todas las observaciones, como se hace ahora mismo con refPeriod, de tal manera que esto no esté insertado directamente en el código de generación. Y dicho esto, se pueden generar los ficheros de metadatos correspondientes.

**Comment by hlafuente** [comment]
No acabo de entender que es lo que se necesita hacer, ¿Me podrías poner un ejemplo?

**Comment by ocorcho** [comment]
Por ejemplo, muchos de los informes son del año 2011, pues pertenecen a ese
censo. Por tanto, sería conveniente no hardcodear la inclusión del año en el
código, sino añadir una nueva columna con el dato constante para que se
rellene en todos los qb:Observation
