### ISSUE TITLE
Informe 01-010022 sin datos para Aragón en sparql endpoint

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#122]
En fuente original sí tiene datos.
Si se pide TC, TM,... sí tiene datos

```sparql
select distinct ?x ?y where {
?obs0 qb:dataSet <http://opendata.aragon.es/recurso/iaest/dataset/01-010022A>.
?obs0 ?x ?y
}
```

**Comment by hlafuente** [comment]
Vamos a provocar la regeneración en el próximo proceso, a ver si vemos porque no se insertan esos datos.

**Comment by MiquelQ** [comment]
Se ha resuelto un problema con los informes que solo tienen una línea en el CSV.
El proceso ya los carga correctamente.
