### ISSUE TITLE
Dimensión (aparentemente) inválida

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#123]
Informes 01-010022 generan una dimensión (creo que) inválida
http://opendata.aragon.es/def/iaest/dimension#fuente-y-fecha

Es fijo en todas las observaciones
De todos modos, no es problema, puede quedarse como está...

``` sparql
select distinct ?y where {
?x <http://opendata.aragon.es/def/iaest/dimension#fuente-y-fecha> ?z .
?x qb:dataSet ?y
}
LIMIT 100
```

**Comment by MiquelQ** [comment]
Se ha cambiado a medida y se trata como un String.

``` sparql
select distinct ?y where {
?x <http://opendata.aragon.es/def/iaest/medida#fuente-y-fecha> ?z .
?x qb:dataSet ?y
}
```
