### ISSUE TITLE
Incluir descripciones para algunas medidas en los DSDs

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#16]
Algunas medidas no incluyen información asociada (_about, comment, label...)
Difieren de cómo se generan en otros casos
Ej. n-accidentes
 /recurso/iaest/dsd/05-0709-070902.json

**Comment by hlafuente** [comment]
Buenas,
Hemos corregido esta incidencia y en la próxima carga de virtuoso se solucionará.
Un saludo.
