### ISSUE TITLE
Referenciada codelist que luego no tiene valores

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#17]
En /recurso/iaest/dsd/01-080101-010105 se referencia a la codelist  /kos/iaest/ccaa-nombre

Pero esta codelist, al consultarla vía API, no tiene valores asociados.

**Comment by ocorcho** [comment]
Esta codelist no debería salir referenciada al tratarse del nombre de una
Comunidad Autónoma, que se asocia a través de sdmx-dim:refArea.
Hugo, mira esto, porque hay que quitar estas columnas de los Excel que se
generan para los metadatos.
