### ISSUE TITLE
Generación errónea de medidas en 01-080101-010105TC

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#20]
Revisar el DSD de 01-080101-010105TC:
* Salen medidas que deberían ser codelist
* Se generan años que en realidad son valores de una codelist

====

select distinct ?p ?o where {
?obs <http://purl.org/linked-data/cube#DataSet> <http://opendata.aragon.es/recurso/iaest/cubo/01-080101-010105TC>.
?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea> <http://opendata.aragon.es/recurso/territorio/Comarca/Gúdar-Javalambre>.
?obs ?p ?o
} LIMIT 100

**Comment by dportoles** [comment]
Otro caso similar: 01-080101-010093

select distinct ?s ?p where {
?obs <http://purl.org/linked-data/cube#DataSet> <http://opendata.aragon.es/recurso/iaest/cubo/01-080101-010093TP>.
?obs ?s ?p
} LIMIT 100

**Comment by hlafuente** [comment]
He creado una incidencia genérica para la parte de 'Salen medidas que deberían ser codelist' #22

**Comment by hlafuente** [comment]
Se corrige en el commit https://github.com/aragonopendata/local-data-aragopedia/commit/f2229c62759db73607c8c39075d262659cf3cdaa
