### ISSUE TITLE
Separador de decimales

### ISSUE THREAD

**Issue by MiquelQ** [aragonopendata/local-data-aragopedia#201]
El ELDA API está mostrando los decimales separados con '.' (punto).
Hay un correo de hace un tiempo en el que César Cano suguiere que lo correcto sería mostrarlos con ',' coma como separador.
Lo primero de todo:
¿Es correcto o es más aconsejable utilizar las nomenclaturas, en las fuentes, que se usan internacionalmente (eso quiere decir normalmente mundo anglosajón)?

En caso de que haya que cambiarlo:
He estado investigando un poco y parece que la forma mas correcta es cambiarlo en la representación (en la API) y no en la inserción a Virtuoso.
¿Sabéis como se hace? 
¿Puede que tenga algo que ver la configuración del idioma?

**Comment by ocorcho** [comment]
@hlafuente analizará las consecuencias del cambio en la representación desde el punto de vista de la reutilización y utilización de los datos, para asegurarnos de que no genere problemas para los reutilizadores.

**Comment by hlafuente** [comment]
Desde el punto de vista de la reutilización, si cambiásemos los decimales a coma la mayoría de los tratamientos que se hagan dejarán de funcionar. Por ejemplo 
generadores de gráficos mediante ficheros, mapeo de información a través de javascript, portales de datos abiertos (CKAN), etc.

Ejemplo practico

He creado dos archivos simples en formato json y los he subido a un ckan que tengo de pruebas, y podéis ver que directamente el json con decimales con coma. Da error y
no permite la visualización. En cambio el mismo json con punto se visualiza correctamente.

Decimales con comas
http://sandbox-ckan.localidata.com/dataset/prueba-decimales/resource/35982aa6-bc56-4422-8c52-d4537992ecca

Decimales con puntos
http://sandbox-ckan.localidata.com/dataset/prueba-decimales/resource/79718414-0dcd-45eb-b3bb-9f6b3a258ac0

**Comment by soyjosem** [comment]
Sería bueno comentarlo con los gestores de la información (IAEST) y contrastar las desventajas desde el punto de vista de los reutilizadores con los beneficios que pueda aportar a su gestión. Intentaremos maximizar las ventajas de la reutilización siempre que la fuente de datos lo permita

**Comment by MiquelQ** [comment]
Se ha modificado la aplicación Aragopedia 2.0 Web para que saque los datos con parte decimal separados por una coma en lugar de un punto.

Se puede ver el resultado en PRE.
http://preopendata.aragon.es/servicios/aragopedia/datos#

![image](https://cloud.githubusercontent.com/assets/16016127/25231867/bda1b5da-25d9-11e7-8f87-7a262714d61c.png)

**Comment by MiquelQ** [comment]
Se ha implementado el cambio en el entorno de PRODUCCIÓN
