### ISSUE TITLE
Actualización datasets con símbolo '%'

### ISSUE THREAD

**Issue by MiquelQ** [aragonopendata/local-data-aragopedia#202]
Con cambio de la issue #198 se sustituyó el carácter '%' por la string 'porcentaje'
Esto ha afectado a mas datasets. Lo que se soluciona cambiando la configuración de estos.
Pero las medidas que contienen ese símbolo(%) también se verían modificadas.

Por ejemplo:

Explotaciones con tierras con >=25% y <50% de su propiedad
ahora es:
http://opendata.aragon.es/def/iaest/medida#explotaciones-con-tierras-con-25-y-50-de-su-propiedad
y sería:
http://opendata.aragon.es/def/iaest/medida#explotaciones-con-tierras-con-25porcentaje-y-50porcentaje-de-su-propiedad

Esto si no me equivoco sería cambiarlo en la ontología. 
¿Sería modificando el html a mano? 
¿Igual que si hay que añadir una nueva medida?

**Comment by MiquelQ** [comment]
En PRE he actualizado algunos 
http://preopendata.aragon.es/recurso/iaest/dataset/03-030006A
http://preopendata.aragon.es/recurso/iaest/dataset/01-010019TP
http://preopendata.aragon.es/recurso/iaest/dataset/04-040003TC

**Comment by hlafuente** [comment]
Si, los cambios hay que hacerlos en las configuraciones del Drive del los cubos de datos afectados y en la ontología. Y en efecto los cambios de la ontología se harían a mano modificando el html.

**Comment by MiquelQ** [comment]
Se ha solucionado el problema, habrá que estar atentos si se crean columnas con el carácter '%' que de machine-name se traducirá a 'porcentaje'
