### ISSUE TITLE
Generada medida municipio en 05-0709-070902 (en vez de refArea)

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#21]
Revisar DSD de 05-0709-070902

Revisar también si debe estar la medida "Dirección provincial nombre"
¿Qué valores debería tener?

**Comment by hlafuente** [comment]
He creado una incidencia genérica para casos como este #22

**Comment by hlafuente** [comment]
En la próxima actualización de datos ya estará bien este caso.
