### ISSUE TITLE
Codelist con un único valor

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#215]
En 01-080101-010110 se hace referencia a la codelist 
http://opendata.aragon.es/kos/iaest/jefe-explotacion.json

la cual solo tiene un valor (1)

¿tiene sentido mantenerla o podría eliminarse esa dimensión?  (entiendo que esta duda se podría generalizar y detectar todas las codelist con un valor, siempre que no sea refArea ni refPeriod)

**Comment by ocorcho** [comment]
Yo creo que aunque tenga sólo un valor no es un problema, puesto que puede haber codificaciones que sólo tengan un valor.
En este caso, lo que no me convence es que ese valor sea el número 1, que no tiene un significado claro. Paso copia de este issue al IAEst para que revisen este campo y nos digan si es correcto.

**Comment by dportoles** [comment]
sí, es una mezcla tanto del hecho de ser un único valor, como del valor que es.
Por eso no afirmaba eliminar todas, sino más bien revisarlas

**Comment by MiquelQ** [comment]
Cambiando la config he conseguido que el proceso cree la nueva dimensión ( iaest-dimension_ocupacion-agraria) en el informe.

http://opendata.aragon.es/recurso/iaest/dataset/01-080101-010110A?api_key=04d08351bc1bf50c3c65beeb8f8f5b13

Pero si se accede a la skos, no la ha creado bien.

http://opendata.aragon.es/kos/iaest/ocupacion-agraria/jefe-explotacion-agraria?api_key=e103dc13eb276ad734e680f5855f20c6

@hlafuente  ¿Esto lo tendría que hacer el proceso?

**Comment by hlafuente** [comment]
Buenas @MiquelQ ,

La configuración que yo veo es esta:

Jefe explotación
jefe-explotacion
iaest-dimension:ocupacion-agraria
dim
skos:Concept
mapping-ocupacion-agraria.xlsx

Para la url del kos se usa el nombre normalizado en este caso:

http://opendata.aragon.es/kos/iaest/jefe-explotacion

Y el fichero mapping-ocupacion-agraria.xlsx creo que no es correcto ya que contiene lo siguiente:

1	http://opendata.aragon.es/kos/iaest/ocupacion-agraria/jefe-explotacion-agraria
2	http://opendata.aragon.es/kos/iaest/ocupacion-agraria/jefe-explotacion-agraria

Y desde mi punto de vista debería de ser:

1	http://opendata.aragon.es/kos/iaest/jefe-explotacion/1
2	http://opendata.aragon.es/kos/iaest/jefe-explotacion/2

Un saludo.

**Comment by MiquelQ** [comment]
Buenas, pero quiero  / queremos (hay un hilo por correo hablando sobre el tema)  que quede:
http://opendata.aragon.es/kos/iaest/ocupacion-agraria/jefe-explotacion-agraria
Que ahora lo hace en el ttl del informe pero no crea el nuevo Skos. 
He creado el mapping: mapping-ocupacion-agraria
¿Para que cree un nuevo skos hay que hacer algo o con cambiar la config debería de valer?
SAludos!

**Comment by hlafuente** [comment]
De forma automática lo que hace es coger el nombre normalizado, en este caso jefe-explotacion y crear un skos con los posibles valores que recibe del csv es decir 1.

Por eso ha creado de forma automática este skos

http://opendata.aragon.es/kos/iaest/jefe-explotacion/1?api_key=04d08351bc1bf50c3c65beeb8f8f5b13

Para que el skos tenga la url

http://opendata.aragon.es/kos/iaest/ocupacion-agraria/jefe-explotacion-agraria?api_key=e103dc13eb276ad734e680f5855f20c6

Tendrás que hacerlo de forma manual. O recibir un csv con el nombre de la columna ocupacion-agraria y que tenga de valores jefe-explotacion-agraria.

**Comment by MiquelQ** [comment]
¿Le podemos decir a Cesar que modifique la definición de la columna en sus informes?
O de lo contrario, creo que deberíamos modificar código para añadir este caso particular.

**Comment by cescan** [comment]
Hola! (me apunto a esta vía...)
Ya he modificado los informes 01-080101-010110
Y también los 01-080101-010113   que tenían el mismo campo.
Ahora tendréis la dimensión "Ocupación agraria" con valor "Jefe explotación agraria"

No se si tendréis que adaptar algo en la configuración...

Saludos!

**Comment by MiquelQ** [comment]
Hola buenas.
Después de esta última actualización se ha creado la dimensión "Ocupación
agraria" con valor "Jefe explotación agraria"
Se puede ver en los Infomres 01-080101-010110 y 01-080101-010113

ej.
http://opendata.aragon.es/recurso/iaest/dataset/01-080101-010113A?_sort=label&_page=0&_pageSize=50&api_key=04d08351bc1bf50c3c65beeb8f8f5b13

SAludos!

**Comment by MiquelQ** [comment]
Se ha modificado desde el IAEST los infomes:
080101-010110 y 01-080101-010113
Se ha cambiado la configuración y ahora crea correctamente esa dimensión.
