### ISSUE TITLE
Problema Google Drive

### ISSUE THREAD

**Issue by MiquelQ** [aragonopendata/local-data-aragopedia#224]
El proceso está fallando debido al parecer, un problema con la API de Google Drive.
En el Log escribe:

> [...] ERROR GoogleDriveAPI:491 - Error en downloadFolderFiles with {"childLink":"https://www.googleapis.com/drive/v2 [...]¡Vaya, este archivo tiene mucho éxito! Podría no estar disponible hasta que esté menos solicitado. <a href="">Inténtalo de nuevo</a>.[...]

Otras veces que ha ocurrido, al día siguiente se ha pasado.
No puede descargar los ficheros del Drive y no completa el proceso.

Es posible que desde la cuenta de google asociada (hlafuente@gmail.com) se pueda hacer algo.

**Comment by ocorcho** [comment]
Hola @MiquelQ 
¿Se ha hecho algún cambio en el sistema desplegado a partir del 16 de octubre? Estamos viendo un uso inusual de la API de Drive desde ese día concretamente.

**Comment by ocorcho** [comment]
Añado a @jcballesteros @hlafuente como referencia en este issue

**Comment by MiquelQ** [comment]
Se ha resuelto el problema con el google Drive.
Se había quedado el proceso enganchado y no paraba de consultar con el Drive sobrepasando el límite de peticiones.
