### ISSUE TITLE
refPeriod como measure en vez de como dimension

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#24]
En algunos casos en los DSD se generan:
http://purl.org/linked-data/sdmx/2009/measure#refPeriod

en lugar de como habitualmente (y creo que es la única forma en SDMX):
http://purl.org/linked-data/sdmx/2009/dimension#refPeriod

Ej: /recurso/iaest/dsd/05-050202.json

Creo que hay más:
select distinct ?s ?p where {?s ?p <http://purl.org/linked-data/sdmx/2009/measure#refPeriod>} LIMIT 100

**Comment by hlafuente** [comment]
Parece que es un error al generar el dsd ya que en los cubos de datos si es correcto.
Por ejemplo en el dsd 03-02010301-030079 tenemos:

<http://opendata.aragon.es/recurso/iaest/dsd/03-02010301-030079> qb:component _:node3egmfx5 .
_:node3egmfx5 qb:measure sdmx-measure:refPeriod .

Pero en el cubo de datos es correcto.

http://alzir.dia.fi.upm.es/recurso/iaest/dataset/03-02010301-030079TP.json?_pageSize=10&_page=0 

Me pongo a trabajar en ello.
