### ISSUE TITLE
En los informes de la categoría 01 y de la categoría 03 el atributo Superficie Útil es tratado de manera distinta

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#28]
En los siguientes informes se utiliza la columna Superficie Útil:
* 01-010003A, 01-010003TC, 01-010003TM, 01-010003TP. En estos casos sus valores se corresponden con los de una codelist
* 03-02010301-030096A, 03-02010301-030096TC, 03-02010301-030096TM, 03-02010301-030096TP. En estos casos sus valores se corresponden con los de una medida

Sería útil utilizar una denominación distinta para la columna en cada uno de los casos, si es posible, para facilitar el proceso de transformación y tratamiento.

**Comment by MiquelQ** [comment]
Se ha igualado los dos campos, ahora se tratan ambos como dimensión.
