### ISSUE TITLE
Medida sin valores en algunos casos

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#31]
En /recurso/iaest/dsd/915-150013.json   (Senado 2008) se informa de una medida llamada Diputados.

Esta medida luego nunca toma valores en sparql endpoint en algunos casos (TC) pero en otros sí toma valores (TP)

select distinct ?x where {
{ ?obs0 <http://purl.org/linked-data/cube#DataSet> <http://opendata.aragon.es/recurso/iaest/dataset/915-150013TP>.
?obs0 ?x ?y
}} LIMIT 1000

select distinct ?x where {
{ ?obs0 <http://purl.org/linked-data/cube#DataSet> <http://opendata.aragon.es/recurso/iaest/dataset/915-150013TC>.
?obs0 ?x ?y
}} LIMIT 1000

**Comment by dportoles** [comment]
Además, por si ayuda, la dimensión orden solo está en TC y no en TP

**Comment by hlafuente** [comment]
Buenas @dportoles,  El cubo 915-150013TP.csv de origen viene con una columna llamada diputados, y el cubo 915-150013TC.csv  y 915-150013TM.csv vienen sin ella. De ahí que en el dsd del cubo 915-150013 aparezca esta columna pero que solo tenga valor para las provincias.

¿Que es lo que necesitas corregir?

**Comment by hlafuente** [comment]
Si, la columna orden es el mismo caso que diputados, solo está en el cubo 915-150013TC.csv

**Comment by dportoles** [comment]
Sí, estaba revisando que viene así en los datos originales... Habrá que ver cómo indicarlo en el DSD, que no será fácil.

Por ahora se puede dejar como está

**Comment by ocorcho** [comment]
En principio, supongo que el orden no sirve para nada, así que @hlafuente propongo que en ese fichero de metadatos de ese cubo se ponga un null en esa columna para que no se exporte a TTL. 
Asimismo, le mandaré a IAEST detalles de esto para que miren si tienen o no que corregirlo, aunque supongo que no, porque los diputados se determinarán por provincias y no por el resto.

**Comment by hlafuente** [comment]
Cambiado el fichero de metadatos. La próxima vez que se regeneren los ttl ya no aparecerán ni diputados ni orden.

**Comment by hlafuente** [comment]
Corregido en https://docs.google.com/spreadsheets/d/1I7cwtqCFh6awbXJ43jCMXOm6PQHtch-NijgrdT-oGP0/edit
