### ISSUE TITLE
Mejorar generación de SKOS con jerarquías

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#33]
Ya se están empezando a generar jerarquías en SKOS, cuando hay dos columnas en algunos cubos que están relacionadas unas con otras. Un ejemplo es el caso de la clase de vivienda, cuyo código completo actual se presenta a continuación:

`
<http://opendata.aragon.es/kos/iaest/clase-vivienda> a skos:ConceptScheme;
	skos:notation "clase-vivienda-agregado";
	rdfs:label "Clase vivienda (agregado)";
	skos:hasTopConcept <http://opendata.aragon.es/kos/iaest/clase-vivienda/colectiva>;
 	skos:hasTopConcept <http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar>.

<http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-no-principal> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "familiar-no-principal";
	skos:prefLabel "Familiar no principal".

<http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-principal> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "familiar-principal";
	skos:prefLabel "Familiar principal".

<http://opendata.aragon.es/kos/iaest/clase-vivienda/colectiva> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "colectiva";
	skos:prefLabel "Colectiva".

<http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "familiar";
	skos:prefLabel "Familiar";
	skos:narrower <http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-no-principal>;
	skos:narrower <http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-principal>.

<http://opendata.aragon.es/kos/iaest/clase-vivienda> a skos:ConceptScheme;
	skos:notation "clase-vivienda-detalle";
	rdfs:label "Clase vivienda (detalle)";
	skos:hasTopConcept <http://opendata.aragon.es/kos/iaest/clase-vivienda/colectiva>;
 	skos:hasTopConcept <http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar>.

<http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-no-principal> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "familiar-no-principal";
	skos:prefLabel "Familiar no principal".

<http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-principal> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "familiar-principal";
	skos:prefLabel "Familiar principal".

<http://opendata.aragon.es/kos/iaest/clase-vivienda/colectiva> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "colectiva";
	skos:prefLabel "Colectiva".

<http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar> a skos:Concept;
	skos:inScheme <http://opendata.aragon.es/kos/iaest/clase-vivienda>;
	skos:notation "familiar";
	skos:prefLabel "Familiar";
	skos:narrower <http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-no-principal>;
	skos:narrower <http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar-principal>.
`

Aún se deben hacer los siguientes cambios (seguramente esto afecte a los metadatos y en algún lugar al código):
* Generar un único ConceptScheme. Actualmente se genera dos veces, con alguna información duplicada, pero con un error en la notation y prefLabel, puesto que se generan en este caso notations y prefLabels para la parte de la jerarquía superior y para la parte inferior. En lugar de generar notations "clase-vivienda-agregada" y "clase-vivienda-detalle" se debería generar uno único "clase-vivienda". Lo mismo ocurre con el prefLabel, que debería ser "Clase vivienda".
* (MINOR) Se generan dos veces las tripletas que describen a la clase vivienda familiar. No es un error, pero si es fácil eliminarlo se podría hacer. 
* (MINOR) Del mismo modo en que se generan los skos:narrower, se podrían generar los skos:broader en el sentido contrario.

**Comment by hlafuente** [comment]
Además en el properties.ttl no se está cambiando correctamente la URL

**Comment by hlafuente** [comment]
@ocorcho Ya está solucionado en Alzir, por si quieres echarle un vistazo.

**Comment by dportoles** [comment]
@hlafuente dónde puedo ver estas jerarquías?
Ni en pre ni en pro estoy encontrándolas ...

**Comment by hlafuente** [comment]
Solo está configurado uno para los cubos de datos 010001, en esta url 'https://docs.google.com/spreadsheets/d/1kYsnPoNizwUrkjq2vDhOLv2LbL8p-GB2pcPsR3o0VWE/edit#gid=791687487' se puede ver que están jerarquizados Clase vivienda (agregado) con Clase vivienda (detalle)

http://opendata.aragon.es/kos/iaest/clase-vivienda.json?api_key=e103dc13eb276ad734e680f5855f20c6

En esa url se puede ver como en clase vivienda se han jerarquizado los valores de agregado y de detalle.

**Comment by dportoles** [comment]
@hlafuente pues en ese ejemplo no veo la diferencia con el resto de codelist.
¿No debería tener narrower, inScheme o algo similar?
¿Como sé que ese valor depende de otro?

**Comment by hlafuente** [comment]
@dportoles La diferencia no está en el primer nivel sino en el segundo, fallo mio que no fue el mejor ejemplo de enlace en el comentario anterior.

Este es un codelist con jerarquía
http://opendata.aragon.es/kos/iaest/clase-vivienda/familiar.json

Y este un codelist sin jerarquía
http://opendata.aragon.es/kos/iaest/horas-trabajadas/11-20.json

Además clase vivienda tiene 3 niveles y horas trabajadas solo 2.
