### ISSUE TITLE
Campo orden a eliminar del DSD porque no aporta nada

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#34]
01-010037TC

(ir añadiendo aquí los que vea que pueden entrar en esta categoría)

**Comment by hlafuente** [comment]
El 01-010037TC corregido en el excel de configuración https://drive.google.com/open?id=1PGaC6jf1cG8zKnUyapm8UhCghZ6u5fcHK8irpm4mu-A

**Comment by dportoles** [comment]
Creo que hay otro en 01-010002
regtenen-orden

**Comment by hlafuente** [comment]
Ok. Como ya tenemos el módulo de mantenimiento, he provocado que esta noche se regenere el cubo 01-010002.

**Comment by hlafuente** [comment]
Por alguna razón se había perdido el cambio del configuración del  01-010037 se ha vuelto a corregir y se provoca la actualización.

**Comment by dportoles** [comment]
@hlafuente  otro con campo orden (elecciones) 915-150006TC

En realidad, creo que son todos los de elecciones:
```sparql
select distinct ?x ?y  where {
?obs qb:dataSet ?x.
?obs <http://opendata.aragon.es/def/iaest/medida#orden> ?z.
?x rdfs:label ?y
} LIMIT 100
```

**Comment by dportoles** [comment]
@MiquelQ ¿Podrías revisar los últimos de elecciones y hacer que no se generen?

**Comment by MiquelQ** [comment]
Se han corregido las configuraciones para que no use esa columna.
Ahora la query devuelve 0 resultados.

``` sparql
select distinct ?x ?y  where {
?obs qb:dataSet ?x.
?obs <http://opendata.aragon.es/def/iaest/medida#orden> ?z.
?x rdfs:label ?y
} LIMIT 100
```
