### ISSUE TITLE
Datos incorrectos del informe 02-020001 (Superficie, densidad de población, serie desde 1996)

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#36]
El informe 02-020001 tiene datos erróneos

Cella tiene los mismos datos que la provincia de Teruel
Las densidades son exageradamente grandes, etc.

Ej de consulta:

select distinct ?territorialUnit ?sup ?dens ?pob where {
{ ?obs0 <http://purl.org/linked-data/cube#DataSet> <http://opendata.aragon.es/recurso/iaest/dataset/02-020001TM>.
?obs0 <http://purl.org/linked-data/sdmx/2009/dimension#refArea> ?territorialUnit.
?obs0 <http://purl.org/linked-data/sdmx/2009/dimension#refPeriod> ?value0 .
FILTER (?value0 = <http://reference.data.gov.uk/id/year/2015>) .
?obs0 <http://opendata.aragon.es/def/iaest/medida#superficie-km2> ?sup .
?obs0 <http://opendata.aragon.es/def/iaest/medida#densidad-de-poblacion-habkm2> ?dens .
?obs0 <http://opendata.aragon.es/def/iaest/medida#poblacion> ?pob .
}} LIMIT 1000

**Comment by dportoles** [comment]
Algo similar ocurre con 02-020002TM

Además, creo que no deberían salir en este informe valores para las provincias, sino solo municipios

**Comment by ocorcho** [comment]
@hlafuente Revisa los datos originales para ver si el error se debe a los datos de partida o al proceso de transformación.

**Comment by hlafuente** [comment]
Buenas,

He detectado el problema y es de la parte de transformación, en algunas condiciones estaba quitando los símbolos a las cadenas de texto incluyendo las medidas que son doubles. Por tanto la superficie en lugar de ser 124,68 estába metiendo 12468.
Lo corrijo y regenero, esto va a pasar con todas las medidas que sean doubles.

Con respecto a los de Teruel he mirado en internet y Teruel es tanto una provincia como un municipio, por eso que también salga un Teruel en los TM.

https://es.wikipedia.org/wiki/Anexo:Municipios_de_la_provincia_de_Teruel

**Comment by dportoles** [comment]
@hlafuente Sí, es provincia y municipio a la vez, pero debe distinguirse
La URI que aparece en la query sparql anterior incluye estos elementos

**Comment by hlafuente** [comment]
Buenas @dportoles creo que ya está corregido, a tu query por cierto quitale el limit 1000 para que aparezcan todos los resultados.

Cuando puedas me confirmas que está todo bien.

**Comment by dportoles** [comment]
@hlafuente Creo que sigue mal puesto que aunque se informa que son tipo double, se generan con comas como separador decimal. Esto creo que impide poder hacer comparaciones aritméticas.

Creo que hay excepciones, pero porque tienen valor exacto. Casualmente para esos valores, no se informa de que es tipo double sino literal.

Además siguen generándose datos para las provincias aunque el informe es tipo TM.
Solo deberían estar valores de municipios (731 en total), por lo que limit 1000 sí debería servir

**Comment by hlafuente** [comment]
Si parece que a virtuoso no le gustan los doubles con , y tiene que ser con . 
De ahí que los valores exactos que metemos en virtuoso el por su cuenta inserta .0 Me pongo a corregirlo.
¿@ocorcho es normal que en los valores doubles no ponga que es un double? 

Con respecto a los de las provincias viene así de origen, pero si no es un dato que no interesa siempre se puede hacer como con la columna orden y es poner en la configuración que no trate esa columna, y así no se generaría. 
Lo que me digais

**Comment by hlafuente** [comment]
Me autocorrijo no se puede quitar la columna provincia en la configuración porque entonces en el TP no aparecería tampoco. Este caso solo lo puede corregir el iaest

**Comment by dportoles** [comment]
@hlafuente Tampoco es grave que salgan provincias. Filtraré la respuesta. Amplío límite a 2000 y ya está.

@ocorcho ¿Quizá pueda ser interesante hacer chequeos de control para detectar estos casos y eliminar automáticamente todos los valores "inapropiados"?  (idea a futuro....)

**Comment by hlafuente** [comment]
@dportoles Ya están los doubles bien cargados, mira a ver si ahora puedes hacer comparaciones aritmeticas.

**Comment by dportoles** [comment]
@hlafuente ahora sí!!

**Comment by hlafuente** [comment]
Se corrige en el commit https://github.com/aragonopendata/local-data-aragopedia/commit/df4c53aa4315ef206f20a643302d7df32ec4cff3
