### ISSUE TITLE
Posible error en informe 03-0300006A

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#39]
En el informe 03-030006A hay un posible error en uno de los datos, creemos. Se trata de la tasa de feminidad, que es una columna que debería dar algún tipo de tasa, pero que aparece en todas las filas como 0.

**Comment by MiquelQ** [comment]
Descargando el CSV (http://bi.aragon.es/analytics/saw.dll?Go&path=/shared/IAEST-PUBLICA/Estadistica%20Local/03/030006A&Action=Download&Options=df&NQUser=granpublico&NQPassword=granpublico) veo que en todas las filas el valor es 0

Esa medida se encuentra solo en ese Informe.

``` sparql
select distinct ?x ?y  where {
?obs qb:dataSet ?x.
?obs <http://opendata.aragon.es/def/iaest/medida#tasa-de-feminidad> ?z.
?x rdfs:label ?y
} 
```

@ocorcho ¿podemos darla por cerrada o le pregunto a Cesar? porque por nuestra parte esta correcto si no me equivoco.

**Comment by cescan** [comment]
Hemos revisado el informe, y el problema lo tiene el informe, que permite descargar esta tasa por sexo, cuando solo tiene sentido por el total (ambos sexos juntos).
Cambiaremos el informe, por lo que cambiará la definición de algunas medidas...

Pero este issue no es error, por lo que lo podeis cerrar.
