### ISSUE TITLE
Mejorar informe de errores de generación de RDF

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#6]
En el proceso de generación de cubos de datos RDF se genera un informe de errores como [este](https://github.com/aragonopendata/local-data-aragopedia/blob/master/data/dump/errorReport.txt). Se debe mejorar los textos:

NO SKOS CONTENT BY CREATE CODELIST

NO FIND CONFIGURATION --> CONFIGURATION FOR THIS COLUMN NOT FOUND

Aparecen también errores sin columnas asociadas (por ejemplo:

03-02010301-030081. ERROR. Column . NO FIND CONFIGURATION

**Comment by hlafuente** [comment]
Buenas, estoy mejorando los errores y mirando el caso concreto de 03-02010301-030081 aparece ese error así, debido a que la cabecera del csv tiene un tabulador que sobra al final de la linea y eso engaña a mi proceso.

Lo que haré será que ponga cadena vacía en estos mensajes.

**Comment by hlafuente** [comment]
Incidencia resuelta
