### ISSUE TITLE
Mejorar las descripciones de las propiedades usadas para dimensiones y medidas en los cubos

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#7]
En el fichero [properties.ttl](https://github.com/aragonopendata/local-data-aragopedia/blob/master/data/dump/DatosTTL/codelists/properties.ttl), que contiene las propiedades usadas como medidas y dimensiones para los cubos de datos, se genera un rdfs:comment que contiene un nombre _feo_, como por ejemplo calse-vivienda-agregado. 

Se debería generar como rdfs:comment el nombre que se utiliza también en el label.

**Comment by hlafuente** [comment]
Incidencia resuelta
