### ISSUE TITLE
Mejorar la generación de SKOS Concept Schemes

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#8]
En el fichero [kos.ttl](https://github.com/aragonopendata/local-data-aragopedia/blob/master/data/dump/DatosTTL/codelists/kos.ttl) se generan los SKOS concept schemes y SKOS concepts que se corresponden con los valores de las dimensiones. 

Se deben hacer los siguientes cambios:

- No generar SKOS Concept Schemes para aquellas propiedades que se transforman en sdmx-dimension:refArea o sdmx-dimension:refPeriod
- El rdfs:label de un skos:ConceptScheme debería ser el nombre bien escrito, y no el código utilizado como skos:notation, siempre que sea posible.

**Comment by hlafuente** [comment]
Para corregir la etiqueta necesito incluir una nueva linea en la configuración, para tener una etiqueta con el label normalizado y sin normalizar.

**Comment by ocorcho** [comment]
Sin problema si esa es la mejor forma de hacerlo y no hay otra opción.

**Comment by hlafuente** [comment]
Finamente no hizo falta cambiar la configuración. En cuanto solucione el resto de bugs hago un push

**Comment by dportoles** [comment]
Hay algunos prefLabel de SKOS que acaban con ",¿" sobrante.
Es en /kos/iaest/regimen-de-tenencia-detalle.json

**Comment by hlafuente** [comment]
Ok, voy a eliminar todo lo que acabe en ",?" si ves alguna cosa más ves diciéndomelo.

**Comment by dportoles** [comment]
select distinct ?s ?o where {
?s <http://www.w3.org/2004/02/skos/core#prefLabel>  ?o
FILTER regex(?o, ",¿")
} LIMIT 100
