### ISSUE TITLE
Errata dimensión extranjeros 03-030070

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#84]
En el DSD de 03-030070

aparecen dos dimensiones que se supone deberían ser iguales (errata)
Extranjeros
Extrenjeros

**Comment by hlafuente** [comment]
La errata no es de la configuracion del proceso si no del iaest, cuando uno se descarga el csv de  03-030070TC

http://bi.aragon.es/analytics/saw.dll?Go&path=/shared/IAEST-PUBLICA/Estadistica%20Local/03/030070TC&Action=Download&Options=df&NQUser=granpublico&NQPassword=granpublico

Se puede ver que una de las columnas es Extrenjeros, en cambio si te descargas el csv de 03-030070A

http://bi.aragon.es/analytics/saw.dll?Go&path=/shared/IAEST-PUBLICA/Estadistica%20Local/03/030070A&Action=Download&Options=df&NQUser=granpublico&NQPassword=granpublico

La columna es Extranjeros

Por tanto hasta que se corrija en el bi.aragon.es no puedo tocar la configuración o perderíamos la medida de las comarcas.
