### ISSUE TITLE
Valores refArea con URI inválidas

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#87]
Hay valores de refArea que no son URI o que son URI incompletas

P.ej.
http://opendata.aragon.es/recurso/territorio/Comarca/

SPARQL query:
``` sparql
select distinct ?refArea where {
 ?obs a qb:Observation.
 ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea>  ?refArea .
}
ORDER by desc  (?refArea)
LIMIT 2000
```

**Comment by hlafuente** [comment]
@dportoles @ocorcho Esto se debe a que hay valores sin rellenar, por ejemplo en la linea 274 del siguiente csv:

http://bi.aragon.es/analytics/saw.dll?Go&path=/shared/IAEST-PUBLICA/Estadistica%20Local/05/050104TC&Options=df&NQUser=granpublico&NQPassword=granpublico

Voy a corregir que no se procese esa linea, pero sería interesante saber si tiene sentido que los datos de origen vengan así.

**Comment by hlafuente** [comment]
@dportoles @ocorcho Solucionado la parte del proceso. Ahora si me llega un área vacía no genero refArea en el cubo de datos.
