### ISSUE TITLE
Valores refArea con URI incorrectas

### ISSUE THREAD

**Issue by dportoles** [aragonopendata/local-data-aragopedia#88]
Hay valores de refArea que son URI aparentemente válidas, pero que realmente no lo son

**Apostaría a que se debe a que estos municipios "inválidos" empiezan por otro que sí es válido => Ej Orihuela (inválido) vs. Orihuela del Tremedal (válido)**

He detectado estos aunque ignoro si hay más:

* http://opendata.aragon.es/recurso/territorio/Municipio/Vic
* http://opendata.aragon.es/recurso/territorio/Municipio/Cascante
* http://opendata.aragon.es/recurso/territorio/Municipio/Cortes
* http://opendata.aragon.es/recurso/territorio/Municipio/Monteagudo
* http://opendata.aragon.es/recurso/territorio/Municipio/Fuentes
* http://opendata.aragon.es/recurso/territorio/Municipio/Torrent
* http://opendata.aragon.es/recurso/territorio/Municipio/Orihuela
* http://opendata.aragon.es/recurso/territorio/Municipio/Peralta
* http://opendata.aragon.es/recurso/territorio/Municipio/Castejón
* http://opendata.aragon.es/recurso/territorio/Municipio/Cervera
* http://opendata.aragon.es/recurso/territorio/Municipio/Foradada
* http://opendata.aragon.es/recurso/territorio/Municipio/Plasencia
* http://opendata.aragon.es/recurso/territorio/Municipio/Linares

SPARQL query:
``` sparql
select distinct ?refArea where {
 ?obs a qb:Observation.
 ?obs <http://purl.org/linked-data/sdmx/2009/dimension#refArea>  ?refArea .
}
ORDER by desc  (?refArea)
LIMIT 2000
```

**Comment by hlafuente** [comment]
Corregido el código, fuerzo la regeneración de los cubos de datos afectados.
