### ISSUE TITLE
Evitar generación de algunas propiedades en los DSDs

### ISSUE THREAD

**Issue by ocorcho** [aragonopendata/local-data-aragopedia#9]
Al generar los DSDs a partir de los ficheros Excel de metadatos, se están generando algunos valores repetidos que son incorrectos. Por ejemplo, en el primero de todos:
`<http://opendata.aragon.es/recurso/iaest/dsd/01-010001> a qb:DataStructureDefinition ;
	rdfs:label "Estructura de los cubos de datos que se corresponden con los informes 01-010001"@es ;
	skos:notation "DSD-01-010001" .

<http://opendata.aragon.es/recurso/iaest/dsd/01-010001> qb:component _:node1egmfx1 .
_:node1egmfx1 qb:dimension sdmx-dimension:refArea .

...

<http://opendata.aragon.es/recurso/iaest/dsd/01-010001> qb:component _:node2egmfx1 .
_:node2egmfx1 qb:dimension sdmx-dimension:refArea .
`

Se genera dos veces el componente con la dimensión refArea, lo que es incorrecto. Esto procede de la unión de varios DSDs que teníamos anteriormente generados, antes de hacer la unión de sus metadatos.

**Comment by hlafuente** [comment]
Incidencia resuelta
